### ISSUE TITLE
Labels management

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#3]
For better issues management, we need a set of labels. Please, leave your version of labels in a comment to this issue

**Comment by roman-dubrovsky** [comment]
My candidates: 

- bug  - some runtime errors or some rule has described (in community or our rules) but isn't being checked
- duplicate - mostly for maintainers. Will set this label before closing some issues
- enhancement - for changing some markdown files, realesing new version and changing some processes (so I prefer to remove `process` label maybe after finishing all current issues)
- feature request - when we're going to add or override some new cop and add a custom 
help wanted 
- high priority - how do you think should we add this label?
- refactoring - instead of `infra`
- postponed
- question
 
I motivated labels from [rubocop gem](https://github.com/rubocop-hq/rubocop/issues). What do you think about it?

**Comment by roman-dubrovsky** [comment]
also, we can add `good first issue`

**Comment by roman-dubrovsky** [comment]
also, we can add `dependencies` for issues and PRs for updating dependencies

**Comment by roman-dubrovsky** [comment]
updated labels by comments above
