### ISSUE TITLE
String Literal quotes

### ISSUE THREAD

**Issue by lazycoder9** [datarockets/datarockets-style#40]
Why double quotes on string literals are preferable?

**Comment by roman-dubrovsky** [comment]
@lazycoder9 I don't exactly remember. This is just more useful for most datarockers (mostly me and @AleksSenkou ). 

Also, in this case, we don't need to change the type of quotes on interpolation (which is really annoying) and can use `'` symbol (which is really useful on printing test descriptions)

**Comment by roman-dubrovsky** [comment]
> can use ' symbol (which is really useful on printing test descriptions)

e.g. 

```ruby
context "when the user's an admin"
```

**Comment by lazycoder9** [comment]
Heard different opinion from @AleksSenkou 😄 But, anyway, if everyone agree with this, had no questions)

**Comment by dzhlobo** [comment]
I also was the one who advocated for double-quotes for the reasons @roman-dubrovsky described:

* no need to change them later when we need to add a `'` symbol or interpolation;
* all the string literals look the same.

**Comment by AleksSenkou** [comment]
I don't like double-quotes. 
* They take space and makes text unnecessary larger, for example: "apple" instead of 'apple'. Really? 😄 
* They show that there is no interpolation or `'` symbol

**Comment by DDKatch** [comment]
@AleksSenkou in your case better to use `:apple` 🙂

**Comment by roman-dubrovsky** [comment]
> I don't like double-quotes.
> They show that there is no interpolation or ' symbol

@AleksSenkou didn't get your point?

**Comment by roman-dubrovsky** [comment]
me too. I don't like double-quotes cause some performance issue. They need more time (need to click two buttons instead of one 😄 )

**Comment by AleksSenkou** [comment]
> They show that there is no interpolation or ' symbol

@roman-dubrovsky I mean single-quotes show that the string is just string without overloading

**Comment by roman-dubrovsky** [comment]
> @AleksSenkou in your case better to use :apple 🙂

JFYI @DDKatch symbols are not equal strings

**Comment by roman-dubrovsky** [comment]
@lazycoder9 can we discuss anything else here? Or we can close this issue?

**Comment by lazycoder9** [comment]
@roman-dubrovsky think everything is clear. Can be closed

**Comment by AleksSenkou** [comment]
@roman-dubrovsky does that mean that we go with double-quotes strings as default?

**Comment by roman-dubrovsky** [comment]
yes, It does

**Comment by roman-dubrovsky** [comment]
@AleksSenkou also I'm wondering. Is `They show that there is no interpolation or ' symbol` a joke?

**Comment by AleksSenkou** [comment]
> Was "They show that there is no interpolation or ' symbol" a joke?

No, it's not a joke. single quotes show that the string is just a string.

**Comment by AleksSenkou** [comment]
> does that mean that we go with double-quotes strings as default?
> yes, It does

I don't like the fact that we didn't make voting or whatever to have results on which we can agree with one of the choices

**Comment by roman-dubrovsky** [comment]
> No, it's not a joke. single quotes show that the string is just a string.

and which reason for this. I can understand it for interpolated string (but also don't understand which benefit we have if the string with interpolation will have another type of quotes. Also, that is really annoying that we need to make some additional changes just for adding interpolation). 

But why should we make some separation between string with and w/o  `'` symbol ? (they are just a string). + in this case, robocop does not allow us to use double quotes too and we should use something like 

```ruby
context 'when the user\'s permissions have admin access`
```

**Comment by roman-dubrovsky** [comment]
> I don't like the fact that we didn't make voting or whatever to have results on which we can agree with one of the choices

@AleksSenkou why should we vote here? It was a `question` issue (no `feature request`) and @lazycoder9 accepted that we can close it after answering. Right?

**Comment by AleksSenkou** [comment]
> why should we vote here?

@roman-dubrovsky I'd like clearly understand that most of us are on double-quotes or single-quotes side. I'd like not to have a situation when someone disagrees and just change cop on own project to use not what we agreed on. 

Anyway, I'd go with voting on most of cops where we have polemic between people

> @lazycoder9 accepted that we can close it after answering. Right?

@roman-dubrovsky it's true. I'm re-raising the question 😄 
For me question is opened

**Comment by roman-dubrovsky** [comment]
@AleksSenkou ok, we can try to make voting but it does not resolve this point for me

> I'd like not to have a situation when someone disagrees and just change cop on own project to use not what we agreed on. 

And happens cause there aren't any comments about points why I prefer double-quotes and no points why we prefer single points from your side (only that this looks pretty (what is really personal) + point about interpolation which I didn't understand and don't get any answers on my question) 

So if we really make voting, for me it'll look like `Oh, man, you have some reasons for this, but it doesn't matter for us. Let's just make voting because of democracy 🎉 `

**Comment by roman-dubrovsky** [comment]
Anyway, let's I repeat my points by this question:

Why I prefer double quotes:

1) We don't need to change the type of quotes when we want to use interpolation or symbols such as `\t`, `\n`,  etc.

```ruby
irb(main):009:0> puts "sd\n\:"
sd
:
=> nil
irb(main):010:0> puts 'sd\n\:'
sd\n\:
=> nil
```

@AleksSenkou  You wrote above that this is cons for you that we can recognize if the string literal has or doesn't have interpolation or special symbols. 

> They show that there is no interpolation or ' symbol

So can you explain to me which benefits we get in this case? Cause for me it looks really annoying. Let's see a typical working case:

- you have some code 

```ruby
def say_hello
  puts 'Hello, Roma'
end
```

- you need to add interpolation here. So you go to the string and adds `#` symbol

```ruby
def say_hello
  puts 'Hello, #Roma'
end
```

- sublime does not make interpolation by default here. So in this case, I just say `Blyat', kak eto zaebalo`, remove symbol `#` and go to change type of quotes

```ruby
def say_hello
  puts "Hello, Roma"
end
```

- now you can add interpolation 

```ruby
def say_hello
  puts "Hello, #{name}"
end
```

So my question: which benefits I can get so that I'll be agreed to make such things? 

Also, we can get similar annoying things with removing interpolation:

E.g. you have some quick fix where you need to remove interpolation. And in these cases, you can skip checking the code locally via rubocop and make a PR for this. And then, when you see the red CI, you'll say `Blyat', kak eto zaebalo` and go running rubocop with autocorrection (and usually need to interrupt your current story)

**Comment by roman-dubrovsky** [comment]
2. we can use ' symbol with double quotes (but in this case, we have an issue with `"` symbol) 

First of all, how can we resolve this issue:

 - use`\` symbol for making all string consistent 

```ruby
'test \''
"test \""
```

- does not make consistent string in this case (rubocop allows to do it)

```
# when style is single quotes
'test'
"test '"

# when style is double quotes
"test"
'test "'
```

The second one, let's discuss when we're using `'` and `"` symbols in the string literals

`'` is our friend on writing good test messages (in the code we should use string literals and prefer locales) cause this symbol is an important part of English language. Yes, some cases we can fix via full form `it 'does not create object' do` instead of `it 'doesn\'t create object' do` but not all cases.

For `"` I know only one case (thank you @atatarenko ) when we need to copy some json or some HTML from a browser (usually in this case it contains `"` symbol)

And the last one: what I prefer to do in this case? 

So coping json or HTML to the code is very uncommon case, so I prefer not to worry about it and just use `'` symbol in this case (cause changing `"` to `\"` in html or json is very annoying). 

Another case with `'` case.  I'm facing with this comment every day, I don't really want to see `\'` or ton of string in Rspecs unconsistent

**Comment by roman-dubrovsky** [comment]
> They take space and makes text unnecessary larger, for example: "apple" instead of 'apple'. Really? 

I don't think so but this is really something which we need to get via voting. But in the current case, for me, this is a minor point cause practical thing more useful than so cosmetical. Does it make sense?

**Comment by roman-dubrovsky** [comment]
The single point, why I prefer to use a single quote that we use it in the eslint config so we don't need to worry about a different type of quotes when we're writing Rails backend with react app (like a habit issue). But this case we can fix via autocorrection

**Comment by TheBlackArroVV** [comment]
So, it's looks like holy war for now, but both variants is about style preference.
And single quotes have also a some preferences. For me its:
1. I understand when it just a word, so it's more easy to find some metamagic
2. It's takes less place, so i better see it's on my laptop's screen and don't need to scroll 
3. It's looks pretty clean(my own opinion)
4. Less buttons need to be clicked
@roman-dubrovsky , for sure, if we want use `\t`, `\n', `'` we can use in this cases double quotes default rubocop rule allows you to do this
And i totally disagree with yours `Blyat', kak eto zaebalo` points, because almost any code editor or ide can be setuped for your rubocop lint and show you errors or in other case you there are many around-commit tools, which will run autocorrect without your manipulations
So, my vote goes to single quotes

**Comment by roman-dubrovsky** [comment]
> I understand when it just a word, so it's more easy to find some metamagic
> It's takes less place, so i better see it's on my laptop's screen and don't need to scroll

@TheBlackArroVV can you explain it more? I don't really understand it. 

> , for sure, if we want use \t, \n, ' we can use in this cases double quotes default rubocop rule allows you to do this

yes, and we have the same issues as for interpolation https://github.com/datarockets/datarockets-style/issues/40#issuecomment-514593556 

> almost any code editor or ide can be setuped for your rubocop lint and show you errors or in other case you there are many around-commit tools, which will run autocorrect without your manipulations

no, there aren't good tools for Sublime editor. (some of them looks good by documentation but have a bad performance) 

And, if we would have this tool, there isn't a tool which will change quotes for interpolation automagically, is there?

**Comment by TheBlackArroVV** [comment]
> @TheBlackArroVV can you explain it more? I don't really understand it.

When i see 'word', and "#{word}" i understand where is just a string from first symbol

> yes, and we have the same issues as for interpolation #40 (comment)

Sure, and i believe, that it's what can be changed for thing, that i described above in this answer

> no, there aren't good tools for Sublime editor. (some of them looks good by documentation but have a bad performance)

So, there many around-commit tools, which works without editor

> And, if we would have this tool, there isn't a tool which will change quotes for interpolation automagically, is there?

Sure, but will it save so much time to make it matter?

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV you forgot about this one

> It's takes less place, so i better see it's on my laptop's screen and don't need to scroll

**Comment by TheBlackArroVV** [comment]
@roman-dubrovsky , o, it's easy
Just 'abc' takes less place then "abc", less place - more characters i can see

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV really? any screenshot with it?

cause the editor should render it with the same width

<img width="304" alt="Screen Shot 2019-07-24 at 4 43 46 PM" src="https://user-images.githubusercontent.com/7738063/61798673-6190fb00-ae32-11e9-9d85-4f147dc5f920.png">

Type 20 symbols

<img width="259" alt="Screen Shot 2019-07-24 at 4 43 41 PM" src="https://user-images.githubusercontent.com/7738063/61798663-5ccc4700-ae32-11e9-8fd8-0ae0e7290684.png">

**Comment by TheBlackArroVV** [comment]
@roman-dubrovsky , hmm, sure, it was my mistake, it's really don't work like this

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV as summary. 1-3 are just cosmetical things

4. It doesn't fix the issue by adding interpolation or special symbols. 

About removing interpolation issue: yes, you're right but this is a very optimistic position (funny to see it from a guy who pushes broken code to github time to time 😉 ). Usually, we have this check on CI and nobody set up it locally. So agreed with your point, only when you set up needed git hook and shared it with other (so that everybody can use it) e.g. via https://github.com/datarockets/dotfiles Otherwise, I don't feel that this point resolved

Does it make sense?

**Comment by AleksSenkou** [comment]
Guysб looks like single/double quotes isn't something that can be discussed with arguments usage. I think that the root is just a personal taste. Sorry, I don't have the energy to leave my thoughts cause it's started to be not productive at all.

My personal taste is one-quote because it's esthetic to me, I like how it looks.
If most of us are for double-quotes - I will use them too.

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I'm sorry but I'm really becoming angry when seeing your comment above. 

First of all, you said that the question is opened and want to discuss it. Ok, I spent some hours and shared you my pain which I faced on my working experience (and I think I left good arguments here). And after that, you want to say that this does not matter and do not want to discuss it.

maybe this isn't a really important issue and we can live with any of styles but why did you want to discuss in this key? 

P.S. I'm really grateful @TheBlackArroVV for his comment cause he also left his pain (I can understand `Less buttons need to be clicked`).

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I didn't want to offend you somehow.

I just don't agree that your points are valuable. This question is nothing just a taste of every exact person. I don't want another "разбор полетов" over here.

Look how much they said about it:
* Those who agreed to use double quotes (thoughtbot) - https://github.com/thoughtbot/guides/pull/174
* Those who agreed to use single quotes (rubocop) - https://github.com/rubocop-hq/ruby-style-guide/issues/96

As you can see none of them had full agreement ^. A lot of people gave arguments to use double quotes and not less to use single quotes

> Guysб looks like single/double quotes isn't something that can be discussed with arguments usage. I think that the root is just a personal taste.

This is what I'm trying to say to you:
![image](https://user-images.githubusercontent.com/3635774/62475156-2c2eca80-b7ad-11e9-9a3f-b40c0899f178.png)

---------------------------------------------------------------------------------

I don't know how to deal with it in our case, one option is just to **disable this rule**, see - https://github.com/rubocop-hq/ruby-style-guide/issues/96#issuecomment-141834351

**Comment by roman-dubrovsky** [comment]
ok, as a summary of this issue:

1) we won't force to use some required rule for this cop. The team or developers use their own decision which rule they will use in the project. 

2) For legacy projects, we can suggest the next suggestion: call rubocop with both rules and choose which has fewer offenses. 

Ping pls if you don't agree with that

**Comment by AleksSenkou** [comment]
@roman-dubrovsky agree 👍
