### ISSUE TITLE
Rails cop:  prefer to use `find_by` instead of `where.first`

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#95]
**Is your feature request related to a problem? Please describe.**
Just detect cases where we're using `where` + `first` together and change it to `find_by`

Use 

```ruby
# bad
DataImport.where("id = ?", params[:data_import_id]).first

# good
DataImport.find_by(id: params[:data_import_id])
```

**Additional context.**
Are there any issues with this cop? In which cases we shouldn't use this rule?

**Comment by AleksSenkou** [comment]
Don't know about edge cases. Both return either nil or record

**Comment by roman-dubrovsky** [comment]
@AleksSenkou maybe are there some side effects if we'll use joins or `includes` before  these statements? Or something else

**Comment by AleksSenkou** [comment]
@roman-dubrovsky `where` adds `ORDER BY id ASC` into sql request. Which doesn't change anything

If default sorting is set, then both will apply it

BTW checked includes and joins - same behavior, data is preloaded or joint

**Comment by roman-dubrovsky** [comment]
> where adds ORDER BY id ASC into sql request.

@AleksSenkou maybe I missed something but it does not add anything. so we have a separate method for this

```
> Workflow.where(moderation_status: :draft).to_sql
=> "SELECT `workflows`.* FROM `workflows` WHERE `workflows`.`moderation_status` = 'draft'"
> Workflow.where(moderation_status: :draft).order(id: :desc).to_sql
=> "SELECT `workflows`.* FROM `workflows` WHERE `workflows`.`moderation_status` = 'draft' ORDER BY `workflows`.`id` DESC"
```

And @AleksSenkou I didn't want to discuss and investigate this issue. But, I checked the that this is not really equal operations

- see the implementation of `find_by` method. This is `where(..).take`. See https://apidock.com/rails/v4.0.2/ActiveRecord/FinderMethods/find_by

- `take` and `first` are not the same methods 

see https://stackoverflow.com/questions/18496421/take-vs-first-performance-in-ruby-on-rails
https://apidock.com/rails/v4.0.2/ActiveRecord/FinderMethods/first
https://apidock.com/rails/v4.0.2/ActiveRecord/FinderMethods/take

But here, looks like it does not really care for us and looks like in most (99% maybe 99,99999%) cases we can change `where.first` to `find_by` .

So I want that the person who starts this issue investigate this question better. Maybe ate there any existing issues in some rubocop repos.

**Comment by AleksSenkou** [comment]
> Workflow.where(moderation_status: :draft).to_sql

I was trying with `.first`

**Comment by roman-dubrovsky** [comment]
@AleksSenkou FYI you can'y run `#to_sql` method for `first` method returned value. Cause `first` return or AR object or Array, but `#to_sql` is a method of AR Relation class

**Comment by AleksSenkou** [comment]
@roman-dubrovsky you are right, but you can still see the logs 😉

**Comment by nikitasakov** [comment]
Yeah, `first` and `take` are not the same.
- `first()` returns first elements ordered by primary key.
- `take()` returns first elements in order according to the database structure.

Just tested:
```ruby
Model.where(field: 2).take(5).pluck(:id)

=> [21879, 21881, 10, 21875, 1]
```

```ruby
Model.where(field: 2).first(5).pluck(:id)

=> [1, 3, 4, 5, 6]
```

So `find_by` is a `where().take`.
And `where().first` and `find_by` are not the same.

In my example:
```ruby
Model.find_by(field: 2).id

=> 21879
```

```ruby
Model.where(field: 2).first.id

=> 1
```

We have to use `where().first` if we need to get record with specific fields and it must be really first (according primary key - usually `id`)

But as I understand the tension is that often we use `where().first` even if we know that this `where()` returns ONLY ONE record and this `first` we write to "convert" array with one element to element. In this case yes - we should use `find_by`. But what about the case that I described above? Looks like sometimes we really need `where().first` construction? Looks like very rare case BTW. 

But we cannot check code execution expectations (developer wants to get first elements by id or developer wants to find specific record and forgot about `find_by` 🤔). 

We can be sure only in this case:
```ruby
where(id: ..., ...).first
```
the same as `find_by(id: ..., ...)`
Please correct me if I mistaking.

My subjective opinion: I would use this rule and remember that you can disable this rule if you have this rare case. It is just seems to me that in 99% of examples we really need `find_by` instead of `where().first`.

As I see rubydoc says that we should use `find_by` instead of `where().first` and `where().take` https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Rails/FindBy

Thoughts?

**Comment by roman-dubrovsky** [comment]
yep, but usually people use `where.first` as `find_by` cause just don't know that method.

But it makes sense not creating a separate cop for that. So I just close this issue

**Comment by connorshea** [comment]
Since `where().first` and `find_by` aren't entirely equivalent, it might be a good idea to open an issue for this in the [rubocop-rails repo](https://github.com/rubocop-hq/rubocop-rails/issues) to at least discuss whether the cop should be autocorrectable.
